// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAddlarnrCrbIkJU3bMp9XQrrGsL0nEToQ',
    appId: '1:361502275044:web:ef3a9e22f4f2715ec703f1',
    messagingSenderId: '361502275044',
    projectId: 'postfirebase-rsrs',
    authDomain: 'postfirebase-rsrs.firebaseapp.com',
    storageBucket: 'postfirebase-rsrs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADAb54mntaK-rvZoQ8k9dwcCltCLzCZQw',
    appId: '1:361502275044:android:f0e57ede7e031f7dc703f1',
    messagingSenderId: '361502275044',
    projectId: 'postfirebase-rsrs',
    storageBucket: 'postfirebase-rsrs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2QUEKexTwCNVa0pc4lQtcs8RTQt2ctsg',
    appId: '1:361502275044:ios:c2cfcc211f8bec35c703f1',
    messagingSenderId: '361502275044',
    projectId: 'postfirebase-rsrs',
    storageBucket: 'postfirebase-rsrs.appspot.com',
    iosClientId: '361502275044-m3vosa9ps6j2e59bsr1upmv8j7koaaj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.postfirebase',
  );
}
